### ISSUE TITLE
Create Tests

### ISSUE THREAD

**Issue by wavecommander** [UPEI-Android/library-journal-entitlements-project#144]
Tests:

        PHP Endpoint testing; test with backend (Docker for integration/e2e tests?)
        Searching a year range yields data containing only that year
        Searching both a start year and end year yields data containing only years in the range
        Searching with Start year only yields data of years from that year on
        Searching with End year only yields data from earliest year to end year
        Searching a single year is overwritten by start year and/or end year
        Searching with special/unicode characters

    Unit Tests:
        Home page:
            Test presence of:
                Logo
                SearchBar:
                    Input
                    Search and filter button:
                        Filter dropdown
                Files being searched list,
                Admin button in top right
            Test functionality:
                Can click and download spreadsheets in 'files being searched' list
        SearchResults page:
            Provide search query = 'C'
            Test presence of:
                Header
                Search results text
                DataTable
            Test functionality:
                Search result text contains query
        SearchBar:
            Test presence of:
                Input bar
                Invisible submit button
                Search and filter button
            Test functionality:
                Can enter text into SearchBar Input
                Can submit form with enter with input in focus
                Can submit form by clicking search and filter button
                Submitting form and clicking Search and filter button causes request to search endpoint
        Header:
            Test presence of:
                Logo
                SearchBar
                TSV button
                Admin button
            Test functionality:
                Clicking logo makes navigate to /
                TSV Button: downloads a well formed TSV file containing DataTable data
                Admin button: causes Admin page to load
        DataTable:
            Test presence of:
                Multiple complete rows
            ? Test antd Table functionality ?
                Maybe test that no errors are thrown on interaction?

    Integration Tests:
        Searching :
            (?) Search result text contains query
            Adding filters with dropdown and submitting form adds params to search endpoint URL
            TSV Button: downloads a well formed TSV file containing DataTable data

    Admin page:
        Let Cal come up with and write the tests; he knows way better than I

**Comment by wavecommander** [comment]
With #147 tests will be automatically run on PR or push to main

**Comment by Ctrain16** [comment]
@wavecommander feel like we could close out this issue as it's pretty general. If you do end up adding more tests you could just create a new issue that is more focused.
